language: node_js
node_js: node
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
before_deploy:
  - npm run build
  - git add -f dist/*
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_KEY
  secret_access_key:
    secure: $AWS_SECRET
  region: $AWS_REGION
  app: $AWS_EB_APP_NAME
  env: $AWS_EB_APP_ENV
  bucket_name: $AWS_S3_BUCKET
  skip_cleanup: true
  on:
    branch: $DEPLOYMENT_BRANCH

