version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ~/mongodb/data/db:/data/db
    networks:
      - mongo
  server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
      - mongo
networks:
  mongo:
    name: mongo