version: "3"
services:
  neo4j:
    image: neo4j:3.0
    ports:
      - 17687:7687
      - 17474:7474
    volumes:
      - ./db/dbms:/data/dbms
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ~/mongodb/data/db:/data/db
  server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017
      JWT_SECRET: AwesomeSecret
      SEED_BD: 'true'